# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Clent CI
on:
  pull_request:
    branches: [ main ]
    paths: [ 'client/**' ]
  push:
    branches: [ main ]
    paths: [ 'client/**' ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint --if-present
      
      - name: Run tests with Jest
        run: npm test -- --coverage
        env:
          CI: true
      
      - name: Build application
        env:
          VITE_API_URL: https://myduka-group-5-kpvg.onrender.com 
        run: npm run build
      
      - name: Test build
        run: |
          ls -la dist/
          test -f dist/index.html
          echo " Build successful"
